/**
 * Auto-generated fields for Provider
 * Generated at: 2026-04-21
 */
export const CustomerFields = [
  {
    key: "id",
    label: "Id",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 1,
    placeholder: "Enter Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: null
  },
  {
    key: "image",
    label: "Image",
    type: "file",
    cell_type: "image",
    display_field: null,
    required: 0,
    placeholder: "Enter Image",
    searchable: false,
    filterable: false,
    sortable: false,
    table_show: true,
    form_show: true,
    options: null
  },
  {
    key: "name",
    label: "Name",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 1,
    placeholder: "Enter Name",
    searchable: true,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  {
    key: "email",
    label: "Email",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 0,
    placeholder: "Enter Email",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
   
  
  {
    key: "package_name",
    label: "Package",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 0,
    placeholder: "",
    searchable: false,
    filterable: false,
    sortable: false,
    table_show: true,
    form_show: false,
    options: null
  },
  {
    key: "posts",
    label: "Count posts",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 0,
    placeholder: "",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  {
    key: "reviews_count",
    label: "Applay Count",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 0,
    placeholder: "",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  {
    key: "is_active",
    label: "Is Active",
    type: "checkbox",
    cell_type: "badge",
    display_field: null,
    required: 1,
    placeholder: "Enter Is Active",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: true,
    form_show: true,
    options: [{ label: 'Active', value: 1, color: 'success' }, { label: 'Inactive', value: 0, color: 'danger' }]
  },
  {
    key: "created_at",
    label: "Created At",
    type: "date",
    cell_type: "date",
    display_field: null,
    required: 0,
    placeholder: "",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
{
  key: "posts",
  label: "my-posts",
  cell_type: "relation_list",
  view_show: true,
  tab: true,  
  headers: [
 {key: "id", label: "ID", format: "short_id" },
 { key: "title", label: "title" },
 { key: "description", label: "description" },
{ key: "price_from", label: "price_from" },
{ key: "price_to", label: "price_to", },
{ key: "image", label: "image", },
{ key: "is_active", label: "is_active", },
    { key: "created_at", label: "Date" },
  ],
  view_route: "/services/view/:id",    
  edit_route: "/services/edit/:id", 
  filterKey: "user_id",
},

,{
  key: "UserContact",
  label: "my-contacts",
  cell_type: "relation_list",
  view_show: true,
  tab: true,  
  headers: [
{ key: "id", label: "ID", format: "short_id" },
    { key: "type", label: "Type" },
    { key: "value", label: "value" },
    { key: "created_at", label: "Date" },
  ],
  view_route: "/services/view/:id",    
  edit_route: "/services/edit/:id", 
  filterKey: "user_id",
},
 

];