/**
 * Auto-generated fields for Provider
 * Generated at: 2026-04-21
 */
export const ProviderFields = [
  {
    key: "id",
    label: "Id",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 1,
    placeholder: "Enter Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: null,
  },
  {
    key: "image",
    label: "Image",
    type: "file",
    cell_type: "image",
    display_field: null,
    required: 0,
    placeholder: "Enter Image",
    searchable: false,
    filterable: false,
    sortable: false,
    table_show: true,
    form_show: true,
    options: null
  },
  {
    key: "name",
    label: "Name",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 1,
    placeholder: "Enter Name",
    searchable: true,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  {
    key: "email",
    label: "Email",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 0,
    placeholder: "Enter Email",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
   
  
  {
    key: "package_name",
    label: "Package",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 0,
    placeholder: "",
    searchable: false,
    filterable: false,
    sortable: false,
    table_show: true,
    form_show: false,
    options: null
  },
  {
    key: "services_count",
    label: "Count Services",
    type: "text",
    cell_type: "progress",
    display_field: null,
    required: 0,
    placeholder: "",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    options: null
  },
  {
    key: "reviews_count",
    label: "Reviews",
    type: "text",
    cell_type: "rating",
    display_field: null,
    required: 0,
    placeholder: "",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  {
    key: "is_active",
    label: "Is Active",
    type: "checkbox",
    cell_type: "badge",
    display_field: null,
    required: 1,
    placeholder: "Enter Is Active",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: true,
    form_show: true,
    options: [{ label: 'Active', value: 1, color: 'success' }, { label: 'Inactive', value: 0, color: 'danger' }]
  },
  {
    key: "created_at",
    label: "Created At",
    type: "ahmed",
    cell_type: "date",
    display_field: null,
    required: 0,
    placeholder: "",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  {
  key: "services",
  label: "Services",
  cell_type: "relation_list",
  view_show: true,

  tab: true,
  headers: [
    { key: "title", label: "Title" },
    { key: "price", label: "Price" },
    { key: "image", label: "Image" },
    { key: "is_active", label: "Active" },
    { key: "desc", label: "Description" },
    { key: "created_at", label: "Date" },
  ],
  view_route: "/Service/view/:id",    
  edit_route: "/Service/edit/:id",  
},
{
  key: "UserContact",
  label: "my-contacts",
  cell_type: "relation_list",
  view_show: true,
  tab: true,  
  headers: [
{ key: "id", label: "ID", format: "short_id" },
    { key: "type", label: "Type" },
    { key: "value", label: "value" },
    { key: "created_at", label: "Date" },
  ],
  view_route: "/services/view/:id",    
  edit_route: "/services/edit/:id", 
  filterKey: "user_id",
},

 {
  key: "projects",
  label: "my-project",
  cell_type: "relation_list",
  view_show: true,
  tab: true,  
  headers: [
{ key: "id", label: "ID", format: "short_id" },
    { key: "title", label: "title" },
    { key: "image", label: "image" },
    { key: "description", label: "description" },
    { key: "project_date", label: "projectDate" },
    { key: "created_at", label: "Date" },
  ],
 
  filterKey: "user_id",
},

 {
  key: "certificates",
  label: "my-certificates",
  cell_type: "relation_list",
  view_show: true,
  tab: true,  
  headers: [
{ key: "id", label: "ID", format: "short_id" },
    { key: "title", label: "title" },
    { key: "image", label: "image" },
    { key: "description", label: "description" },
    { key: "issue_date", label: "issue Date" },
    { key: "created_at", label: "Date" },
  ],
 
  filterKey: "user_id",
},
{
  key: "my-packages",
  label: "my-packages",
  cell_type: "relation_list",
  view_show: true,
  tab: true,  
  headers: [
{ key: "id", label: "ID", format: "short_id" },
    { key: "packageName", label: "packageName" },
    { key: "starts_at", label: "startsAt" },
    { key: "ends_at", label: "ends At" },
    { key: "active", label: "active" },
    { key: "created_at", label: "Date" },
  ],
 
  filterKey: "user_id",
},
{
  key: "my-branches",
  label: "my-branches",
  cell_type: "relation_list",
  view_show: true,
  tab: true,  
  headers: [
{ key: "id", label: "ID", format: "short_id" },
    { key: "title", label: "title" },
    { key: "address", label: "address" },
    { key: "mobile", label: "mobile" },
{ key: "location.map_link", label: "Location", format: "link" },
    { key: "created_at", label: "Date" },
  ],
 
  filterKey: "user_id",
},
{
  key: "verification",
  label: "my-verification",
  cell_type: "relation_list",
  view_show: true,
  tab: true,  
  headers: [
{ key: "id", label: "ID", format: "short_id" },
    { key: "id_card_front", label: "id cart",format:"image" },
    { key: "id_card_back", label: "id cart",format:"image" },
    { key: "commercial_register", label: "id cart",format:"image" },
    { key: "tax_card", label: "text card" },
    { key: "notes", label: "notes" },
    { key: "status", label: "status" },
 
  ],

  filterKey: "user_id",
},

];