
 
export const ServiceFields = [
  { 
    key: "id", 
    label: "Id", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    options: null
  },
  { 
    key: "user_id", 
    label: "User Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "user.name",
    required: 0, 
    placeholder: "Enter User Id",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: false,
    form_show: true,
    endpoint: 'users',
    relation_fields: 'id,name',
    options: { label: 'name', value: 'id' }
  },
  { 
    key: "category_id", 
    label: "Category Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "category.name",
    required: 0, 
    placeholder: "Enter Category Id",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: false,
    form_show: true,
    endpoint: 'categories',
    relation_fields: 'id,name',
    options: { label: 'name', value: 'id' }
  },
  { 
    key: "city_id", 
    label: "City Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "city.name",
    required: 0, 
    placeholder: "Enter City Id",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: false,
    form_show: true,
    endpoint: 'cities',
    relation_fields: 'id,name_ar',
    options: { label: 'name_ar', value: 'id' }
  },
  { 
    key: "title", 
    label: "Title", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Title",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "desc", 
    label: "Desc", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Desc",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "image", 
    label: "Image", 
    type: "file", 
    cell_type: "image",
    display_field: null,
    required: 1, 
    placeholder: "Enter Image",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "price", 
    label: "Price", 
    type: "number", 
    cell_type: "number",
    display_field: null,
    required: 1, 
    placeholder: "Enter Price",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
    { 
    key: "views_count", 
    label: "views count", 
    type: "number", 
    cell_type: "number",
    display_field: null,
    required: 0, 
    placeholder: "Enter Price",
    searchable: false,
    filterable: false,
    sortable: false,
    table_show: true,
    form_show: false,
    options: null
  },
  { 
    key: "is_active", 
    label: "Is Active", 
    type: "checkbox", 
    cell_type: "badge",
    display_field: null,
    required: 1, 
    placeholder: "Enter Is Active",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: true,
    form_show: true,
    options: [{ label: 'Active', value: 1, color: 'success' }, { label: 'Inactive', value: 0, color: 'danger' }]
  },
  { 
    key: "created_at", 
    label: "Created At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Created At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  { 
    key: "updated_at", 
    label: "Updated At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Updated At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: null
  },

   {
  key: "reviews",
  label: "my-reviews",
  cell_type: "relation_list",
  view_show: true,
   form_show: false, 
  tab: true,  
  headers: [
{ key: "id", label: "ID", format: "short_id" },
 { key: "user_name", label: "user_name" },
    { key: "user_image", label: "user_image" },
    { key: "rating", label: "rating" ,format:"rating"},
    { key: "comment", label: "comment" },
    { key: "service_name", label: "service_name" },
   
     { key: "created_at", label: "Date" },
  ],
  view_route: "/services/view/:id",    
  edit_route: "/services/edit/:id", 
  filterKey: "user_id",
},
 {
  key: "visits",
   form_show: false, 
  label: "my-visits",
  cell_type: "relation_list",
  view_show: false,
  tab: true,  
  headers: [
{ key: "id", label: "ID", format: "short_id" },
    { key: "ip_address", label: "ip_address" },
    { key: "country", label: "country" },
    { key: "city", label: "city" },
    { key: "device_type", label: "device_type" },
    { key: "os", label: "os" },
    { key: "browser", label: "browser" },
    { key: "created_at", label: "Date" },
  ],
  view_route: "/services/view/:id",    
  edit_route: "/services/edit/:id", 
  filterKey: "user_id",
},
];