/**
 * Auto-generated fields for User
 * Generated at: 2026-04-21 09:27:06
 */
export const UserFields = [
  { 
    key: "id", 
    label: "Id", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    options: null,
    view_show: false, 
  },
   { 
    key: "image", 
    label: "Image", 
    type: "file", 
    cell_type: "image",
    display_field: null,
    required: 0, 
    placeholder: "Enter Image",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null,
     view_show: true, 
  },
  { 
    key: "name", 
    label: "Name", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Name",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null,
     view_show: true, 
  },
  { 
    key: "email", 
    label: "Email", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    view_show: true, 
    required: 0, 
    placeholder: "Enter Email",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
  key: "password", 
  label: "Password", 
  type: "password", 
  cell_type: "text",
  display_field: null,
  required: 1, 
  placeholder: "Enter Password",
  searchable: false,
  filterable: false,
  sortable: false,
  table_show: false,
  form_show: true,
  options: null
},
  { 
    key: "phone", 
    label: "Phone", 
    type: "text", 
    cell_type: "text",
    view_show: true, 
    display_field: null,
    required: 0, 
    placeholder: "Enter Phone",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "user_name", 
    label: "User Name", 
    type: "text", 
    view_show: true, 
    cell_type: "text",
    display_field: null,
    required: 0, 
    placeholder: "Enter User Name",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    options: null
  },
 
  { 
    key: "whtsapp", 
    label: "Whtsapp", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 0, 
    placeholder: "Enter Whtsapp",
    searchable: false,
    filterable: false,
    sortable: false,
    table_show: false,
    form_show: false,
    options: null
  },
  { 
    key: "country_code", 
    label: "Country Code", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Country Code",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    options: null
  },
  { 
    key: "is_active", 
    label: "Is Active", 
    type: "checkbox", 
    cell_type: "badge",
    display_field: null,
    required: 1, 
    placeholder: "Enter Is Active",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: true,
    form_show: true,
    options: [{ label: 'Active', value: 1, color: 'success' }, { label: 'Inactive', value: 0, color: 'danger' }]
  },
  { 
    key: "email_verified_at", 
    label: "Email Verified At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Email Verified At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: null
  },
  { 
    key: "role", 
    label: "Role", 
    type: "select", 
    cell_type: "badge",
    display_field: null,
    required: 0, 
    placeholder: "Enter Role",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: true,
    form_show: true,
    options: [{ label: "User", value: 'user' }, { label: "Super_Admin", value: 'super_admin' }]
  },
  { 
    key: "social_type", 
    label: "Social Type", 
    type: "select", 
    cell_type: "badge",
    display_field: null,
    required: 0, 
    placeholder: "Enter Social Type",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: [{ label: "Google", value: 'google' }, { label: "Apple", value: 'apple' }, { label: "Facebook", value: 'facebook' }]
  },
  
  { 
    key: "city_id", 
    label: "City Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "city.name",
    required: 0, 
    placeholder: "Enter City Id",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: false,
    form_show: true,
    endpoint: 'cities',
    relation_fields: 'id,name_en',
    options: { label: 'name_en', value: 'id' }
  },
  { 
    key: "info", 
    label: "Info", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 0, 
    placeholder: "Enter Info",
    searchable: true,
    filterable: false,
    sortable: false,
    table_show: false,
    form_show: true,
    options: null
  },
  { 
    key: "last_login_at", 
    label: "Last Login At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Last Login At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: null
  },
  { 
    key: "created_at", 
    label: "Created At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Created At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  { 
    key: "updated_at", 
    label: "Updated At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Updated At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: null
  }
];